language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/go-isatty
  - go get github.com/mitchellh/gox
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
after_success:
  - ./build.sh
deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - "dist/darwin_386_logcatf.zip"
    - "dist/darwin_amd64_logcatf.zip"
    - "dist/linux_386_logcatf.zip"
    - "dist/linux_amd64_logcatf.zip"
    - "dist/linux_arm_logcatf.zip"
    - "dist/windows_386_logcatf.zip"
    - "dist/windows_amd64_logcatf.zip"
  on:
    all_branches: true
    tags: true
